### PR TITLE
Redo input plugin

### LINKED ISSUE #15: Make input and output generic/minimize code duplication
Something like this can also be implemented for input, maybe we can do something more generic for both of them?

_Originally posted by @BlackPhlox in https://github.com/BlackPhlox/bevy_midi/pull/12#discussion_r939655190_

### PR DESCRIPTION
**Pull request by grace125**
# Objective 

- Fix #15

`MidiInputPlugin` currently relies on stdin/stdout to connect to midi ports, and provides no API to change the current port connected to. 

## Solution

- Rely on `bevy_log` wherever possible
- Change configuration options of  `MidiInputSettings`
- Change API to resemble `MidiOutputPlugin`
- Change examples accordingly

### CODE REVIEW

**Comment by BlackPhlox** [comment]
I tested the `piano` example. It seems that there is some issues with handling input now, might be delay oriented.

I recorded my actions as shown by the current `0.6` branch

`0.6` branch:
old

The same actions but for this PR
new

**Comment by grace125** [comment]
@BlackPhlox Okay I have a hunch for what was happening.

A crossbeam_channel guarantees is that every consumer can receive a message at most once. Bevy guarantees that a `Resource` won't be cloned. Thus, if two systems call `try_recv` from a resource's `Receiver`, they probably won't get the same set of messages. 

In my code I opted to make `MidiRawData` an `Event` for the guarantee that every system can see each `MidiRawData` once. Would you be able to test if you still observe this issue?

**Comment by BlackPhlox** [comment]
Great! Though, I will first be able to test this in about 12 hours ish.

**Comment by BlackPhlox** [comment]
Yep, it's fixed now! 🚀

**Comment by BlackPhlox** [comment]
Running `cargo clippy -- --D clippy::pedantic` shows that `async` of  `midi_output` is not using await along with some other stuff. I'm not sure as I haven't used async before. But I think that handling(or use expect or documenting it) some of the unwraps might be good, I can take a look at it if you want me to :)

**Comment by grace125** [comment]
Sure!

**Pull request merged**
